### ISSUE TITLE
File copied but Kindle's lockscreen unchanged

### ISSUE THREAD

**Issue by austinliuu** [Underknowledge/underknowledge.puppeteer-homeassistant#2]
From the log I see 
```
pupeteer | Dimensions: { width: 561, height: 758, deviceScaleFactor: 1.350000023841858 }
pupeteer | Warning: Permanently added 'ip' (ECDSA) to the list of known hosts.
pupeteer | 
pupeteer | 
pupeteer | Welcome to Kindle!
pupeteer | 
pupeteer | copyed
```
and I can see the home_assistant_8bit.png file at /mnt/us/documents, but the screen unchanged. Anything I'm missing? I'm using PW4

**Comment by Underknowledge** [comment]
Hey! Sorry for being late, Just seen. I have to fix up my notifications.
Try to SSH into your kindle and run this manually. 
't -g /mnt/us/documents/home_assistant_8bit.png'
For now, I think that epis might not in $PATH
here the "man" page https://wiki.mobileread.com/wiki/Eips

**Comment by austinliuu** [comment]
I tried '`t -g /mnt/us/documents/home_assistant_8bit.png`' and it says "`-sh: t: not found`"
I tried the eips commend and it looks like running `eips -g /mnt/us/documents/home_assistant_8bit.png` **directly** in ssh session is working instead

**Comment by austinliuu** [comment]
One thing I noticed is that the image does not scale to full screen, is there a way to put epis commend for that?
![image](https://user-images.githubusercontent.com/30453289/218380777-0f8f3396-ff70-4c03-9d4c-b8a7c087547c.jpg)

**Comment by Underknowledge** [comment]
`t` is a typo, should be `eips` Strange that it does not want to do stuff then..
Do me a favour and exec into the container, and run the part of the script interactively and tell me what it spits out

```bash
docker exec -it pupeteer
export KINDLE_IP="YOUHAVETOSETTHEIPHEREPLZ"
sshpass -p "${KINDLE_PASSWORD}" ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@${KINDLE_IP} 'eips -g /mnt/us/documents/home_assistant_8bit.png
```

while in the container, you could try this too, and let me know if this works better (encapsulating epis in a sh cmd)
```bash
sshpass -p "${KINDLE_PASSWORD}" ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@${KINDLE_IP} sh -c 'eips -g /mnt/us/documents/home_assistant_8bit.png
```

**Comment by austinliuu** [comment]
Would like to help debugging but I recently sold my Mac and the container keep crashing when I ran it in my Windows(both in Windows and WSL Ubuntu) 😔
With the log saying `2023-02-13 20:42:54 pupeteer  | /usr/bin/env: 'bash\r': No such file or directory`

**Comment by austinliuu** [comment]
Here is what I see
```
> docker exec -it pupeteer /bin/bash
node@pupeteer:/opt/puppeteer$ export KINDLE_IP="myip"
node@pupeteer:/opt/puppeteer$ sshpass -p "${KINDLE_PASSWORD}" ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@${KINDLE_IP} 'eips -g /mnt/us/documents/home_assistant_8bit.png'
Warning: Permanently added 'myip' (ECDSA) to the list of known hosts.


Welcome to Kindle!

sh: eips: not found
```

and running the second code section showed a similar error
```
node@pupeteer:/opt/puppeteer$ sshpass -p "${KINDLE_PASSWORD}" ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@${KINDLE_IP} sh -c 'eips -g /mnt/us/documents/home_assistant_8bit.png'
Warning: Permanently added 'myip' (ECDSA) to the list of known hosts.


Welcome to Kindle!

-g: line 1: eips: not found
```

**Comment by austinliuu** [comment]
And tried in native ssh session, it works, so the issue was with docker shell?
```
~ % ssh root@myip
[root@kindle root]# eips -g /mnt/us/documents/home_assistant_8bit.png
update_to_display: update_mode=PARTIAL, wave_mode=2 inverted=0
swipe feature is not supported in this platfom G2
```

**Comment by zabojpetr** [comment]
It is because the command is executed with non-login shell (do not ask me why, I'm linux noob, see [explanation](https://unix.stackexchange.com/questions/493287/command-not-found-when-using-ssh-and-non-absolute-commands)). 
So login to kindle via ssh and type `which eips` to get full path to eips (for me `/usr/sbin/eips`)
Then replace all `eips` in `homeassistant.sh` with full path (eg. `/usr/sbin/eips`)
And then run `docker compose up --build` to rebuild image to get new `homeassistant.sh` to container.

**Comment by Underknowledge** [comment]
yea, now I know thats a PATH issue, I will change the pupeteer flags anyway, so why not also fix this
