### ISSUE TITLE
Help with Puppeteer on HAOS Please

### ISSUE THREAD

**Issue by neil1111** [Underknowledge/underknowledge.puppeteer-homeassistant#3]
Hi. I'm running HAOS on a RPI. I'd like to use the Node Red https://flows.nodered.org/node/node-red-contrib-puppeteer-core nodes, but I can't figure out how to get Puppeteer installed under HAOS.  Or, if installation of these nodes include Puppeteer, they don't seem to work. I thought you might have some advice, based on the impressive Docker setup you created.

I can't find any other Home Assistant-Puppeteer documentation.
Thanks!
Neil

**Comment by Underknowledge** [comment]
Apparently I'm late for the party, 
Almost a year with just a couple days extra!
Sorry - I have not seen your message. 
I just expect you figured it out or moved to greener fields ;)
