### ISSUE TITLE
High disk usage - puppeteer always create new chrome profile

### ISSUE THREAD

**Issue by zabojpetr** [Underknowledge/underknowledge.puppeteer-homeassistant#4]
Hi,

I find out that puppeteer creates Chrome profile every time, when it starts, but at the end it not remove it. The size of profile is about 4MB. The profiles are located at `/tmp`.

Puppeteer has parameter to use specific profile, so then it not create new profiles.

In `home_assistant.js` to the [puppeteer launch](https://github.com/Underknowledge/underknowledge.puppeteer-homeassistant/blob/5429535e4a6cfb3aabac56bd83df1ec950f22d3a/home_assistant.js#L15C42-L21C4) add parameter `userDataDir: '/tmp/puppeteer_chrome_profile',` or different path to the profile. If the profile does not exists it is created.

**Comment by Underknowledge** [comment]
Hi, Quite fun that someone even uses it. 
I mean you already have the solution? Want to do a pull request or should I quickly just commit? 
as an FYI, sibbl made an heavyer effort to spin up a Project. 
[sibbl/hass-lovelace-kindle-screensaver](https://github.com/sibbl/hass-lovelace-kindle-screensaver)

**Comment by zabojpetr** [comment]
Hi,

you can do the commit. I looked at that project too, but not tested yet. And it looks like, that there will be the same problem :D
